### ISSUE TITLE
Xcode 10 and i386

### ISSUE THREAD

**Issue by groue** [swiftlyfalling/SQLiteLib#31]
Hello @swiftlyfalling,

I'm currently unable to build SQLiteLib with Xcode 10 beta, due to the use of i386 in the `ARCHS[sdk=macosx*]` setting of the amalgamation target.

I find that Xcode is pretty picky, since the mere *presence* of the architecture creates an error, even when nobody *actually* builds for i386. Remove i386 from ARCHS, and Xcode becomes happy.

I don't quite know how to solve this trouble. Do you think I should create a radar, according to my above interpretation, hoping Xcode 10 eventually becomes less sensitive? Or do you think SQLiteLib will have to drop support for i386 (here or in a fork dedicated to GRDB)?

**Comment by swiftlyfalling** [comment]
Hi @groue!

Thank you for the heads-up. (I haven't had a chance to download the beta yet.)

Does changing `ARCHS[sdk=macosx*]` to `$(ARCHS_STANDARD)` resolve the issue for you?

**Comment by groue** [comment]
I will try, and tell you!

**Comment by groue** [comment]
Moved to #32
