### ISSUE TITLE
SQLite 3.30.1

### ISSUE THREAD

**Issue by groue** [swiftlyfalling/SQLiteLib#44]
Hello @swiftlyfalling,

SQLite 3.30.1 is out. May I request a push access to the repository so that i can bump SQLiteLib?

**Comment by groue** [comment]
Thanks ;-) 🙇 !

**Comment by swiftlyfalling** [comment]
Apologies for the delay - I've invited you for push access (and also have a PR #45 currently working through CI to update to SQLite 3.30.1).

**Comment by groue** [comment]
Don't be sorry, that's exactly why I offered my humble support :-)
